### ISSUE TITLE
List of headers in Jäschke not correctly sorted ?

### ISSUE THREAD

**Issue by julkamny** [Esukhia/tibetan-sort-python#2]
Hello,

I am very thankful for all the hard work put in creating this sorting tool, it's priceless. I have just finished compiling the list of all headers in Jäschke's Tibetan-English dictionary (London, 1881). When I sort the headers, the result differs from the original list. Wasurs seem to cause issues for sure, maybe there's more to uncover. 

Given a query word in Tibetan, my overall goal is simply to be able to immediately find the page in the dictionary where the corresponding entry lies / might lie : I have already succeeded, and I find this shenanigan quite useful, but I'm curious about the discrepancies between Jäschke's order and that of the sorting algorithm. 

You'll find in my repository the list (which must for sure contain typos) and the very poor script I've written to conduct the trial, my apologies for the awful code.

By the way, would you happen to know if a similar list of headers for the dictionary of Sarat Chandra Das exists?

With thanks,
Julien
https://github.com/julkamny/tibetan_jottings

**Comment by eroux** [comment]
Hi Julien,

Thanks for your bug report and for your works, that's very interesting! May I ask you the context of your work? people interested in Tibetan lexicography and NLP are quite rare! There are some lexicographical resources I can share with you if you contact me by email (my address is in my github profile)

The order implemented in this repository is the one from the *bod rgya tshig mdzod chen mo* of 1985. While the general order is the same as Jäschke, there are some possible variations, for the wasur, long vowels, retroflex, etc. See [this article](https://himalaya.socanth.cam.ac.uk/collections/journals/ret/pdf/ret_63_02.pdf) for some insights on the topic, and [this blogpost](https://www.bdrc.io/blog/2021/10/29/sorting-out-tibetan-alphabetical-order/) for some technical details (sorry for the shameless publicity). We don't really have a plan to implement all possible variations (especially since some lexicon sort by alphabetical order on the final syllable of words, see Maurer 2018), but we'd be happy to accept a patch! If you think there are bugs in this implementation (in the sense that it doesn't respect the order of the 1985 dictionary), I'd be happy to fix them though

Best wishes,
Elie

**Comment by julkamny** [comment]
Hello Elie,

Thank you for taking the time to give me such a detailed reply, I am very grateful! I had come across your blogpost but had not yet read your article, I found it highly enlightening. I have corrected quite a few mistakes in the Jäschke headers file (most were due to my hasty typing, some to typos in the dictionary itself), and my impression now is that the only discrepancy between the order of the bod rgya tshig mdzod chen mo and that of Jäschke concerns the wasur. There is also one case where the lexicographer does not seem to follow his own rules, p. 454 : མཚའ་ལུ་ | མཚགས་, which is not consistent with p. 82 for instance དགག་པ་ | […] | དགབ་པ་ | དགའ་བ་

I would have found it rewarding to tweak the algorithm so that it handles the wasur correctly, but I am far from being able to fully understand the logic implemented in tibetan_sort.py. I dared to try to tinker with it, writing for instance on line 100 'ཤ', 'ཤྭ’, 'ཥ' but of course the outcome did not match my expectations.

My interest in Tibetan collation rules has a very narrow, practical focus: I want to be able to browse Jäschke’s dictionary (and soon that of Das) in PDF format briskly. Eventually, I suppose such a tool would be useful to many other people studying Classical Tibetan (which is my case). One could picture a website which, given a query, would show you the scan of the correct page in these dictionaries. Am I wrong to believe that what I describe does not exist yet? In the case of Das’s work, I’m aware of a [quite costly version](https://www.pktcshop.com/product-p/scd-mac.htm); what I envision of course would be free.

Again, thanks for your encouraging words and interest in my amateur trifles!

**Comment by eroux** [comment]
Hi Julien,

I think this is an interesting project, thanks a lot!

I have to say I'm a bit overwhelmed at the moment so I can't really look at how to implement the order in Jäschke's dictionary (I can't remember exactly how the rules work)...

On a side note, I'm browsing Bialek's textbook of Classical TIbetan and I find it interesting that she recommends Jäschke...

Best wishes,
Elie

**Comment by julkamny** [comment]
Hi Élie,

Thank you for your kind words. It is indeed Bialek's comment (p. 155) on the unreliability of online dictionaries and her praises of Jäschke / Das prompted me to carry out this small experiment. I place high hopes, like everyone interested in Tibetan I guess, in the completion of the [Tibetisches Wörterbuch](https://wts.badw.de/woerterbuch-digital.html).

I'm happy to report that I have found a very simple solution to my issue: simply disregard the wasur, that is delete the bytes that represent it from both the list of headers and the user's query. Then everything, quite logically, works like a charm. I guess there might be cases where a one-page discrepancy between the nearest page and the one returned by the script occurs, but I can live with that.

Best,
Julien
